eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    
    
      
        
microservice:
  account-service:
    endpoints:
      endpoint:
        uri: http://account-service/account
  customer-service:
    endpoints:
      endpoint:
        uri: http://customer-service/customer    
